### ISSUE TITLE
How do i use this? =) I love this concept. 

### ISSUE THREAD

**Issue by KeepCreatingOnline** [chmac/nostr-map#3]

**Comment by chmac** [comment]
There's a version deployed somewhere, and then you can build a map, where all the points get saved to nostry. Then you get a URL that you can share with folks to view your map. I don't know off the top of my head where it's deployed, but you could also deploy a copy yourself. The code is fairly documented.

I'll close this issue now as we're not actively providing support for this. If you are running the code and hit specific issues you're welcome to open new issues, although I can't promise that we'll be able to reply.
